### ISSUE TITLE
Handling scheduled events on an internet browser

### ISSUE THREAD

**Issue by sgthale** [HighIntensityPaint/demo-web-project#3]
Since we are working on the PC module first, we have to figure out how to code in notifications on the web browser. Yahoo! email requests for your permission whenever you go to the email page to display pop-up notifications for incoming emails. I suggest we get around the documentation for this and hijack this pipeline.

**Comment by tddome** [comment]
This can compliment the suggested alarm feature that Chris posted about, and looks like will be the core elements of this web service. Once I help with the alarms feature, I can help tie this together with it, if wanted.

**Comment by tddome** [comment]
Notifications have been coded in successfully into the web browser, along with alarms being connected to them.
