### ISSUE TITLE
Recent reminders feature

### ISSUE THREAD

**Issue by ghost** [HighIntensityPaint/demo-web-project#6]
This should be a minimum priority but a feed that shows the most recent reminders or reminders that are expected to come up soon could be useful.

**Comment by tddome** [comment]
I wanted to add and say the priority of this may be increased from low to medium; if people are to be notified of what is coming up, seeing an early reminder can be a good option if they don't want to be notified the moment they have to address something. For example, on my calendar app, I always use a feature that notifies me of an event an hour before for certain events (e.g. doctor, hair, or other appointment), 15 min prior for others like leaving for work soon, and right-on-time for things like taking medication. With these considerations in mind, recent reminders seems like the second-best step after figuring out immediate reminders.

**Comment by tddome** [comment]
Recent reminders can be checked with the Alarm Check button, so long as they don't refresh the page after an alarm has triggered. No time to refine this further.
